/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Abre una conversacion. El cliente guarda el token y lo reenvia siempre.
         */
        post: operations["create_session_chat_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Session
         * @description Si hay sesion y cuando vence. El panel no puede leer la cookie: pregunta aqui.
         */
        get: operations["current_session_metrics_session_get"];
        put?: never;
        /**
         * Open Session
         * @description Cambia la clave por una sesion en una cookie HttpOnly que vence.
         */
        post: operations["open_session_metrics_session_post"];
        /**
         * Close Session
         * @description Borra la cookie. El token sigue siendo valido hasta que vence (ver
         *     app.api.panel_session), pero el navegador ya no lo tiene.
         */
        delete: operations["close_session_metrics_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description Las cifras principales del periodo: clientes, pedidos, reservas, embudo y costo.
         */
        get: operations["summary_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeseries
         * @description Un punto por dia del periodo, con los dias sin actividad en cero.
         */
        get: operations["timeseries_metrics_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Products
         * @description Los productos con mas interes, los mas pedidos, los que faltaron y lo que
         *     se busco sin encontrar.
         */
        get: operations["products_metrics_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operations
         * @description Como trabajo el agente: resultado de los turnos, tokens y cache, herramientas
         *     usadas y costo por dia.
         */
        get: operations["operations_metrics_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Heatmap
         * @description Conversaciones y turnos por dia de la semana y hora, en la hora del negocio:
         *     cuando hace falta mas gente atendiendo.
         */
        get: operations["heatmap_metrics_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatsapp/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Webhook
         * @description Handshake de Meta al registrar la URL en el panel.
         *
         *     Meta manda el verify token que uno pego alla; si coincide, se le devuelve
         *     el `challenge` tal cual y la URL queda registrada.
         */
        get: operations["verify_webhook_whatsapp_webhook_get"];
        put?: never;
        /** Receive */
        post: operations["receive_whatsapp_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatsapp/media/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Media
         * @description Reenvia una foto del backend para que Meta la pueda descargar.
         */
        get: operations["media_whatsapp_media__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /**
             * Session Token
             * @description Token devuelto por POST /chat/session. Identifica la conversacion.
             */
            session_token: string;
            /** Message */
            message: string;
        };
        /**
         * ChatResponse
         * @description El front puede pintar el pedido y la reserva en vivo sin volver a
         *     preguntar: el estado de los borradores viaja junto a la respuesta.
         */
        ChatResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Reply */
            reply: string;
            /** Draft */
            draft: components["schemas"]["DraftLineView"][];
            /** Draft Total */
            draft_total: string;
            /** Placed Order Id */
            placed_order_id?: string | null;
            /** Missing Fields */
            missing_fields: string[];
            /** Images */
            images?: components["schemas"]["ImageView"][];
            reservation?: components["schemas"]["ReservationView"] | null;
            /** Placed Reservation Id */
            placed_reservation_id?: string | null;
        };
        /** CostStats */
        CostStats: {
            /** Turns */
            turns: number;
            /** Failed Turns */
            failed_turns: number;
            /** Total Usd */
            total_usd: string | null;
            /** Per Conversation Usd */
            per_conversation_usd: string | null;
        };
        /** CustomerStats */
        CustomerStats: {
            /** Unique */
            unique: number;
            /** New */
            new: number;
            /** Returning */
            returning: number;
        };
        /** DayPoint */
        DayPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Conversations */
            conversations: number;
            /** Orders */
            orders: number;
            /** Gross Sales */
            gross_sales: string;
            /** Reservations */
            reservations: number;
        };
        /** DraftLineView */
        DraftLineView: {
            /** Product Id */
            product_id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Subtotal */
            subtotal: string;
        };
        /**
         * Funnel
         * @description Las conversaciones que empezaron en el periodo y hasta donde llegaron.
         *
         *     Cada paso incluye a los siguientes: quien hizo un pedido tambien cuenta como
         *     interesado aunque no haya buscado, porque ya sabia lo que queria.
         */
        Funnel: {
            /** Conversations */
            conversations: number;
            /** Interested */
            interested: number;
            /** With Cart */
            with_cart: number;
            /** With Order */
            with_order: number;
            /** With Reservation */
            with_reservation: number;
            /** Abandoned Carts */
            abandoned_carts: number;
            /** Conversion Rate */
            conversion_rate: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoffCount */
        HandoffCount: {
            /** Kind */
            kind: string;
            /** Handoffs */
            handoffs: number;
        };
        /** HandoffStats */
        HandoffStats: {
            /** Total */
            total: number;
            /** By Kind */
            by_kind: components["schemas"]["HandoffCount"][];
        };
        /** HeatCell */
        HeatCell: {
            /** Weekday */
            weekday: number;
            /** Hour */
            hour: number;
            /** Conversations */
            conversations: number;
            /** Turns */
            turns: number;
            /** Days */
            days: number;
        };
        /**
         * Heatmap
         * @description Cuando escriben los clientes: dia de la semana por hora.
         */
        Heatmap: {
            period: components["schemas"]["Period"];
            /** Cells */
            cells: components["schemas"]["HeatCell"][];
        };
        /**
         * ImageView
         * @description Una imagen que acompana la respuesta.
         *
         *     Viaja aparte del texto para que cada canal la muestre como le corresponde:
         *     el chat web la pinta dentro de la burbuja y WhatsApp la envia como adjunto.
         */
        ImageView: {
            /** Url */
            url: string;
            /** Caption */
            caption?: string | null;
            /** Product Id */
            product_id?: string | null;
        };
        /**
         * LatencyStats
         * @description Cuanto espero el cliente por la respuesta: modelo, herramientas y backend.
         */
        LatencyStats: {
            /** Measured Turns */
            measured_turns: number;
            /** P50 Seconds */
            p50_seconds: number | null;
            /** P90 Seconds */
            p90_seconds: number | null;
        };
        /** ModelCount */
        ModelCount: {
            /** Model */
            model: string;
            /** Turns */
            turns: number;
            /** Cost Usd */
            cost_usd: string | null;
        };
        /** OperationsDay */
        OperationsDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Turns */
            turns: number;
            /** Failed Turns */
            failed_turns: number;
            /** Cost Usd */
            cost_usd: string | null;
            /** Cache Hit Rate */
            cache_hit_rate: number | null;
        };
        /**
         * OperationsStats
         * @description Como trabajo el agente, no que vendio: fallos, tokens, cache, herramientas.
         */
        OperationsStats: {
            period: components["schemas"]["Period"];
            /** Turns */
            turns: number;
            /** Outcomes */
            outcomes: components["schemas"]["OutcomeCount"][];
            /** Average Iterations */
            average_iterations: number | null;
            tokens: components["schemas"]["TokenStats"];
            /** Tools */
            tools: components["schemas"]["ToolCount"][];
            latency: components["schemas"]["LatencyStats"];
            /** Models */
            models: components["schemas"]["ModelCount"][];
            handoffs: components["schemas"]["HandoffStats"];
            voice_notes: components["schemas"]["VoiceStats"];
            /** Daily */
            daily: components["schemas"]["OperationsDay"][];
        };
        /** OrderStats */
        OrderStats: {
            /** Placed */
            placed: number;
            /** Cancelled */
            cancelled: number;
            /** Gross Sales */
            gross_sales: string;
            /** Net Sales */
            net_sales: string;
            /** Average Ticket */
            average_ticket: string | null;
        };
        /** OutcomeCount */
        OutcomeCount: {
            /** Outcome */
            outcome: string;
            /** Turns */
            turns: number;
        };
        /** PanelLogin */
        PanelLogin: {
            /** Key */
            key: string;
        };
        /** PanelSession */
        PanelSession: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * Period
         * @description Un rango de dias completos, en la hora del negocio, con ambos extremos
         *     incluidos: del 1 al 30 de septiembre es el 30 entero.
         *
         *     "Hoy" empieza a medianoche en Bogota, no en UTC. Cortar por UTC le pasaria
         *     las ventas de las siete de la noche al dia siguiente.
         */
        Period: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Timezone */
            timezone: string;
        };
        /** ProductCount */
        ProductCount: {
            /** Product Id */
            product_id: string;
            /** Name */
            name: string;
            /** Conversations */
            conversations: number;
            /** Units */
            units?: number | null;
        };
        /** ProductStats */
        ProductStats: {
            period: components["schemas"]["Period"];
            /** Most Interest */
            most_interest: components["schemas"]["ProductCount"][];
            /** Most Ordered */
            most_ordered: components["schemas"]["ProductCount"][];
            /** Out Of Stock */
            out_of_stock: components["schemas"]["ProductCount"][];
            /** Failed Searches */
            failed_searches: components["schemas"]["SearchCount"][];
        };
        /** ReservationStats */
        ReservationStats: {
            /** Placed */
            placed: number;
            /** Cancelled */
            cancelled: number;
            /** Guests */
            guests: number;
        };
        /**
         * ReservationView
         * @description La reserva en construccion. `starts_at` va en ISO con zona, para que el
         *     front la formatee en la del visitante sin tener que adivinar cual era.
         */
        ReservationView: {
            /** Starts At */
            starts_at?: string | null;
            /** Duration Minutes */
            duration_minutes: number;
            /** Party Size */
            party_size?: number | null;
            /** Notes */
            notes?: string | null;
            /** Missing Fields */
            missing_fields: string[];
        };
        /** SearchCount */
        SearchCount: {
            /** Query */
            query: string;
            /** Times */
            times: number;
        };
        /** SessionRequest */
        SessionRequest: {
            /**
             * Channel
             * @default web
             */
            channel: string;
        };
        /**
         * SessionResponse
         * @description El token es opaco: el cliente lo guarda y lo reenvia, no lo interpreta.
         */
        SessionResponse: {
            /** Session Token */
            session_token: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** Summary */
        Summary: {
            period: components["schemas"]["Period"];
            customers: components["schemas"]["CustomerStats"];
            orders: components["schemas"]["OrderStats"];
            reservations: components["schemas"]["ReservationStats"];
            funnel: components["schemas"]["Funnel"];
            cost: components["schemas"]["CostStats"];
        };
        /** Timeseries */
        Timeseries: {
            period: components["schemas"]["Period"];
            /** Points */
            points: components["schemas"]["DayPoint"][];
        };
        /**
         * TokenStats
         * @description Los cuatro cubos de tokens del periodo, sumados.
         */
        TokenStats: {
            /** Input */
            input: number;
            /** Output */
            output: number;
            /** Cache Read */
            cache_read: number;
            /** Cache Write */
            cache_write: number;
            /** Cache Hit Rate */
            cache_hit_rate: number | null;
        };
        /** ToolCount */
        ToolCount: {
            /** Tool */
            tool: string;
            /** Calls */
            calls: number;
            /** Turns */
            turns: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceStats */
        VoiceStats: {
            /** Notes */
            notes: number;
            /** Transcribed */
            transcribed: number;
            /** Transcribed Seconds */
            transcribed_seconds: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_chat_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_metrics_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelSession"];
                };
            };
        };
    };
    open_session_metrics_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PanelLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_session_metrics_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    summary_metrics_summary_get: {
        parameters: {
            query?: {
                /** @description Solo las conversaciones de este canal: web, whatsapp. Por defecto, todas. */
                channel?: string | null;
                /** @description Primer dia, incluido. Por defecto, hace 29 dias. */
                start_date?: string | null;
                /** @description Ultimo dia, incluido. Por defecto, hoy. */
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeseries_metrics_timeseries_get: {
        parameters: {
            query?: {
                /** @description Solo las conversaciones de este canal: web, whatsapp. Por defecto, todas. */
                channel?: string | null;
                /** @description Primer dia, incluido. Por defecto, hace 29 dias. */
                start_date?: string | null;
                /** @description Ultimo dia, incluido. Por defecto, hoy. */
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeseries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    products_metrics_products_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Solo las conversaciones de este canal: web, whatsapp. Por defecto, todas. */
                channel?: string | null;
                /** @description Primer dia, incluido. Por defecto, hace 29 dias. */
                start_date?: string | null;
                /** @description Ultimo dia, incluido. Por defecto, hoy. */
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operations_metrics_operations_get: {
        parameters: {
            query?: {
                /** @description Solo las conversaciones de este canal: web, whatsapp. Por defecto, todas. */
                channel?: string | null;
                /** @description Primer dia, incluido. Por defecto, hace 29 dias. */
                start_date?: string | null;
                /** @description Ultimo dia, incluido. Por defecto, hoy. */
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_metrics_heatmap_get: {
        parameters: {
            query?: {
                /** @description Solo las conversaciones de este canal: web, whatsapp. Por defecto, todas. */
                channel?: string | null;
                /** @description Primer dia, incluido. Por defecto, hace 29 dias. */
                start_date?: string | null;
                /** @description Ultimo dia, incluido. Por defecto, hoy. */
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Heatmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_webhook_whatsapp_webhook_get: {
        parameters: {
            query?: {
                "hub.mode"?: string;
                "hub.verify_token"?: string;
                "hub.challenge"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_whatsapp_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    media_whatsapp_media__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
